CREATE TABLE lab_test_Word(
	Wordcode varchar(10) NULL,
	Wordname varchar(50) NULL
)

INSERT INTO lab_test_Word (Wordcode, Wordname) VALUES ('NP', 'POSITIVE')
, ('NP', 'NEGATIVE')
, ('APP', 'CLEAR')
, ('QUAN', '10')
, ('QUAN', '20')
, ('QUAN','15')
, ('APP','OPAQUE')
, ('APP','HAZY')
, ('APP','SLIGHTLY HAZY')
, ('APP','TURBID')
, ('APP','SLIGHTLY TURBID')
, ('AP','ABSENT')
, ('AP','PRESENT')
, ('REA','REACTIVE')
, ('REA','NON-REACTIVE')
, ('PH','ACIDIC')
, ('PH','ALKLINE')
, ('PH','7.0')
, ('PH','7.5')
, ('PH','8.0')
, ('SEEN','SEEN')
, ('SEEN','NOT-SEEN')
, ('Colour','PALE YELLOW')
, ('Colour','GREYISH WHITE')
, ('Colour','YELLOW')
, ('Colour','DEEP YELLOW')
, ('Colour','REDDISH')
, ('Colour','STRAW')
, ('Colour','')

